export { default as Vacancies } from './Vacancies'
export { default as Candidates } from './Candidates'
export { default as Clients } from './Clients'
export { default as Partners } from './Partners'
export { default as Events } from './Events'
